spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
AUTH_SERVICE_URL_LOCAL=localhost:8080
COURSE_SERVICE_URL_LOCAL=localhost:8081
DASHBOARD_SERVICE_URL_LOCAL=localhost:8082
# URL konfigurasi untuk Feign clients
services.auth.baseurl=http://localhost:8080
services.course.baseurl=http://localhost:8081
services.dashboard.baseurl=http://localhost:8082
services.course.api-key=test-courses-api-key
services.dashboard.api-key=test-dashboard-api-key
JWT_SECRET_KEY=test-jwt-secret-key
jwt.secret-key=test-jwt-secret-key
server.port=8080