spring.application.name=udehnih-payment
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres?user=postgres.qwaxpgjaovcvffvgqvow&password=MxZFpLDZVivqiZ35
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update